package main

import (
	"context"
	"fmt"
	"github.com/scagogogo/npm-crawler/pkg/registry"
)

func main() {

	// 使用默认参数创建registry
	//registry := registry.NewRegistry()
	//fmt.Println(registry)

	// 使用特定的选项创建registry
	options := registry.NewOptions().SetRegistryURL(registry.RegistryUrlCnpm)
	registry := registry.NewRegistry(options)
	registryInformation, err := registry.GetRegistryInformation(context.Background())
	if err != nil {
		panic(err)
	}
	fmt.Println(registryInformation.ToJsonString())
	// Output:
	// {"db_name":"","engine":"mysql","doc_count":3421729,"doc_del_count":0,"update_seq":36424254,"purge_seq":0,"compact_running":false,"sizes":{"active":0,"external":0,"file":0},"disk_size":0,"data_size":0,"other":{"data_size":0},"instance_start_time":"2023-08-23T08:44:00.891Z","disk_format_version":0,"committed_update_seq":0,"compacted_seq":0,"uuid":""}

	// 获取包的信息
	packageInformation, err := registry.GetPackageInformation(context.Background(), "requests")
	if err != nil {
		panic(err)
	}
	fmt.Println(packageInformation.ToJsonString())
	// Output:
	// {"_id":"requests","_rev":"80356-61be4770cbabbe39b0462e03","name":"requests","description":"An streaming XHR abstraction that works in browsers and node.js","dist-tags":{"latest":"0.3.0","next":""},"versions":{"0.0.1":{"name":"requests","version":"0.0.1","description":"requests","main":"./lib/main.js","scripts":{"test":"echo \"Error: no test specifi
	//ed\" \u0026\u0026 exit 1","start":""},"repository":null,"keywords":null,"author":{"name":"solos","email":"solos@solos.so"},"license":"MIT","bugs":null,"homepage":"","dependencies":null,"devDependencies":null,"_id":"requests@0.0.1","dist":{"shasum":"ad84864ffbfbd52d6c81d5dabd9856667734dda4","tarball":"https://r2.cnpmjs.org/requests/-/requests-0.0.1.
	//tgz","integrity":"sha512-/8Gv92qGO/KUAheqNDOT9qDmJk0/aedecP0CrJyOBMXlNwQccWPYfOxfFRyba9Yq6ZcfMBG4H/sZnSc5mRZXeQ==","signatures":null},"_from":".","_npmVersion":"1.3.24","_npmUser":{"name":"solos","email":"solos@solos.so"},"maintainers":[{"name":"3rdeden","email":"npm@3rd-Eden.com"}],"directories":{},"deprecated":""},"0.1.0":{"name":"requests","vers
	//ion":"0.1.0","description":"An XHR abstraction that works in browsers and node.js","main":"index.js","scripts":{"test":"mocha test/test.js","start":"node test/development.js"},"repository":{"type":"git","url":"https://github.com/unshiftio/requests"},"keywords":["request","xhr","requests","http","xml","xmlhttp","xmlhttprequest"],"author":{"name":"Ar
	//nout Kazemier","email":""},"license":"MIT","bugs":{"url":"https://github.com/unshiftio/requests/issues"},"homepage":"https://github.com/unshiftio/requests","dependencies":{"axo":"0.0.x","eventemitter3":"0.1.x","loads":"0.0.x"},"devDependencies":{"assume":"1.2.x","browserify":"8.x.x","istanbul":"0.3.x","mocha":"2.2.x","pre-commit":"1.0.x"},"_id":"re
	//quests@0.1.0","dist":{"shasum":"4633ba0842e454f8a03f4237ecad9bb5efda4bd2","tarball":"https://r2.cnpmjs.org/requests/-/requests-0.1.0.tgz","integrity":"sha512-YzcVZS7S0JrAXxsElgQng7n/MqnDzGuNAOrVGE+NufFNWZI/TjGsGAR3Sa7psPjyhiyb9GiRI0Jh4cgC0VqFtQ==","signatures":null},"_from":".","_npmVersion":"2.7.5","_npmUser":{"name":"3rdeden","email":"npm@3rd-Ede
	//n.com"},"maintainers":[{"name":"3rdeden","email":"npm@3rd-Eden.com"}],"directories":{},"deprecated":""},"0.1.1":{"name":"requests","version":"0.1.1","description":"An XHR abstraction that works in browsers and node.js","main":"index.js","scripts":{"test":"mocha test/test.js","start":"node test/development.js"},"repository":{"type":"git","url":"http
	//s://github.com/unshiftio/requests"},"keywords":["request","xhr","requests","http","xml","xmlhttp","xmlhttprequest"],"author":{"name":"Arnout Kazemier","email":""},"license":"MIT","bugs":{"url":"https://github.com/unshiftio/requests/issues"},"homepage":"https://github.com/unshiftio/requests","dependencies":{"axo":"0.0.x","eventemitter3":"0.1.x","han
	//g":"1.0.x","loads":"0.0.x","xhr-send":"1.0.x"},"devDependencies":{"assume":"1.2.x","browserify":"8.x.x","istanbul":"0.3.x","mocha":"2.2.x","pre-commit":"1.0.x"},"_id":"requests@0.1.1","dist":{"shasum":"82285a029f279074f15894ca93d79a9256105ece","tarball":"https://r2.cnpmjs.org/requests/-/requests-0.1.1.tgz","integrity":"sha512-f43Vfd+WD7pVl1IxntQm/m
	//c3Q4aPafvXAoYX3v6sktd+vJfXo6WoeNDh/7kaE+AqhdlNeN6BIcS/F6zMX4Ox9g==","signatures":null},"_from":".","_npmVersion":"2.7.5","_npmUser":{"name":"3rdeden","email":"npm@3rd-Eden.com"},"maintainers":[{"name":"3rdeden","email":"npm@3rd-Eden.com"}],"directories":{},"deprecated":""},"0.1.2":{"name":"requests","version":"0.1.2","description":"An XHR abstracti
	//on that works in browsers and node.js","main":"index.js","scripts":{"test":"node test/index.js","start":"node test/development.js"},"repository":{"type":"git","url":"https://github.com/unshiftio/requests"},"keywords":["request","xhr","requests","http","xml","xmlhttp","xmlhttprequest"],"author":{"name":"Arnout Kazemier","email":""},"license":"MIT","
	//bugs":{"url":"https://github.com/unshiftio/requests/issues"},"homepage":"https://github.com/unshiftio/requests","dependencies":{"axo":"0.0.x","eventemitter3":"0.1.x","hang":"1.0.x","loads":"0.0.x","xhr-send":"1.0.x"},"devDependencies":{"assume":"1.2.x","async-each":"0.1.x","browserify":"8.x.x","istanbul":"0.3.x","mocha":"2.2.x","mochify":"2.7.x","p
	//re-commit":"1.0.x"},"_id":"requests@0.1.2","dist":{"shasum":"312f4f44e64ca9d18e1523dd616a8a34a7ccd46f","tarball":"https://r2.cnpmjs.org/requests/-/requests-0.1.2.tgz","integrity":"sha512-YFq5fwL7Kr6od3b51lxeiyLERx+beW7NCrQ3kMTlK/7S/BVvZOYWpsr26zYE60VrulVVlfIArpYNK06fTWBHfg==","signatures":null},"_from":".","_npmVersion":"2.7.5","_npmUser":{"name":"
	//3rdeden","email":"npm@3rd-Eden.com"},"maintainers":[{"name":"3rdeden","email":"npm@3rd-Eden.com"}],"directories":{},"deprecated":""},"0.1.3":{"name":"requests","version":"0.1.3","description":"An XHR abstraction that works in browsers and node.js","main":"index.js","scripts":{"test":"node test/index.js","start":"node test/development.js"},"reposito
	//ry":{"type":"git","url":"https://github.com/unshiftio/requests"},"keywords":["request","xhr","requests","http","xml","xmlhttp","xmlhttprequest"],"author":{"name":"Arnout Kazemier","email":""},"license":"MIT","bugs":{"url":"https://github.com/unshiftio/requests/issues"},"homepage":"https://github.com/unshiftio/requests","dependencies":{"axo":"0.0.x"
	//,"eventemitter3":"0.1.x","hang":"1.0.x","loads":"0.0.x","xhr-send":"1.0.x"},"devDependencies":{"assume":"1.2.x","async-each":"0.1.x","browserify":"8.x.x","extendible":"0.1.1","istanbul":"0.3.x","mocha":"2.2.x","mochify":"2.7.x","pre-commit":"1.0.x"},"_id":"requests@0.1.3","dist":{"shasum":"7ceadbdb066edde40c32cbe604fd51ae926179b0","tarball":"https:
	////r2.cnpmjs.org/requests/-/requests-0.1.3.tgz","integrity":"sha512-g2tmQGceoDf6vG9rHseIPh8REI5ZjlurSq/ExqZAi14kVqiRiK5LUJoME0+49KPwuQotr9p+QnIPFAGu+oJ9lg==","signatures":null},"_from":".","_npmVersion":"2.7.5","_npmUser":{"name":"3rdeden","email":"npm@3rd-Eden.com"},"maintainers":[{"name":"3rdeden","email":"npm@3rd-Eden.com"}],"directories":{},"dep
	//recated":""},"0.1.4":{"name":"requests","version":"0.1.4","description":"An XHR abstraction that works in browsers and node.js","main":"index.js","scripts":{"test":"node test/index.js","start":"node test/development.js"},"repository":{"type":"git","url":"https://github.com/unshiftio/requests"},"keywords":["request","xhr","requests","http","xml","xm
	//lhttp","xmlhttprequest"],"author":{"name":"Arnout Kazemier","email":""},"license":"MIT","bugs":{"url":"https://github.com/unshiftio/requests/issues"},"homepage":"https://github.com/unshiftio/requests","dependencies":{"axo":"0.0.x","eventemitter3":"0.1.x","extendible":"0.1.x","hang":"1.0.x","loads":"0.0.x","xhr-send":"1.0.x"},"devDependencies":{"ass
	//ume":"1.2.x","async-each":"0.1.x","browserify":"8.x.x","istanbul":"0.3.x","mocha":"2.2.x","mochify":"2.7.x","pre-commit":"1.0.x"},"_id":"requests@0.1.4","dist":{"shasum":"209ba6297d197896f5b3ba5becc24bdf0b2c01b8","tarball":"https://r2.cnpmjs.org/requests/-/requests-0.1.4.tgz","integrity":"sha512-JO/LMxo+d2wCn0pgyAeZeRjZJgXK8A840JVlBF2VmmtGy7tbCO5J6
	//rGYwlN8kPeq/qzJojhfZsGUTHFjilgdnQ==","signatures":null},"_from":".","_npmVersion":"2.7.5","_npmUser":{"name":"3rdeden","email":"npm@3rd-Eden.com"},"maintainers":[{"name":"3rdeden","email":"npm@3rd-Eden.com"}],"directories":{},"deprecated":""},"0.1.5":{"name":"requests","version":"0.1.5","description":"An XHR abstraction that works in browsers and n
	//ode.js","main":"index.js","scripts":{"test":"node test/index.js","start":"node test/development.js"},"repository":{"type":"git","url":"https://github.com/unshiftio/requests"},"keywords":["request","xhr","requests","http","xml","xmlhttp","xmlhttprequest"],"author":{"name":"Arnout Kazemier","email":""},"license":"MIT","bugs":{"url":"https://github.co
	//m/unshiftio/requests/issues"},"homepage":"https://github.com/unshiftio/requests","dependencies":{"axo":"0.0.x","eventemitter3":"0.1.x","extendible":"0.1.x","hang":"1.0.x","loads":"0.0.x","xhr-send":"1.0.x"},"devDependencies":{"assume":"1.2.x","async-each":"0.1.x","browserify":"8.x.x","istanbul":"0.3.x","mocha":"2.2.x","mochify":"2.7.x","pre-commit"
	//:"1.0.x"},"_id":"requests@0.1.5","dist":{"shasum":"8aab6f391e65b6af9ffaaa3141c3f6403a5321c6","tarball":"https://r2.cnpmjs.org/requests/-/requests-0.1.5.tgz","integrity":"sha512-RlVkKK2pSdn7y15OttdPbNOy/o88fmzdb2Mlkh29DYsHcRuAEbAKRLkq9qRBn0qnLW00J7J5/Lihj7+NvJpziQ==","signatures":null},"_from":".","_npmVersion":"1.4.28","_npmUser":{"name":"3rdeden",
	//"email":"npm@3rd-Eden.com"},"maintainers":[{"name":"3rdeden","email":"npm@3rd-Eden.com"}],"directories":{},"deprecated":""},"0.1.6":{"name":"requests","version":"0.1.6","description":"An streaming XHR abstraction that works in browsers and node.js","main":"index.js","scripts":{"test":"node test/index.js","start":"node test/development.js"},"reposit
	//ory":{"type":"git","url":"git+https://github.com/unshiftio/requests.git"},"keywords":["request","xhr","requests","http","xml","xmlhttp","xmlhttprequest"],"author":{"name":"Arnout Kazemier","email":""},"license":"MIT","bugs":{"url":"https://github.com/unshiftio/requests/issues"},"homepage":"https://github.com/unshiftio/requests","dependencies":{"axo
	//":"0.0.x","eventemitter3":"0.1.x","extendible":"0.1.x","hang":"1.0.x","loads":"0.0.x","xhr-send":"1.0.x"},"devDependencies":{"assume":"1.2.x","async-each":"0.1.x","browserify":"8.x.x","http-proxy":"1.11.x","istanbul":"0.3.x","mocha":"2.2.x","mochify":"2.7.x","pre-commit":"1.0.x","setheader":"0.0.x"},"_id":"requests@0.1.6","dist":{"shasum":"f9770176
	//8419e62235656f392025844fbb1ed3d2","tarball":"https://r2.cnpmjs.org/requests/-/requests-0.1.6.tgz","integrity":"sha512-VTxaW7bvERYfPfjuVrYQIVSTPlIp8Wx4QDcmMO8k8RJKbNDXesU8zTBhzTb9qC5sV+5fTJxJdn6wFHhNSwBMZg==","signatures":null},"_from":".","_npmVersion":"2.9.1","_npmUser":{"name":"3rdeden","email":"npm@3rd-Eden.com"},"maintainers":[{"name":"3rdeden"
	//,"email":"npm@3rd-Eden.com"}],"directories":{},"deprecated":""},"0.1.7":{"name":"requests","version":"0.1.7","description":"An streaming XHR abstraction that works in browsers and node.js","main":"index.js","scripts":{"test":"node test/index.js","start":"node test/development.js"},"repository":{"type":"git","url":"git+https://github.com/unshiftio/r
	//equests.git"},"keywords":["request","xhr","requests","http","xml","xmlhttp","xmlhttprequest"],"author":{"name":"Arnout Kazemier","email":""},"license":"MIT","bugs":{"url":"https://github.com/unshiftio/requests/issues"},"homepage":"https://github.com/unshiftio/requests","dependencies":{"axo":"0.0.x","eventemitter3":"1.1.x","extendible":"0.1.x","hang
	//":"1.0.x","loads":"0.0.x","xhr-send":"1.0.x"},"devDependencies":{"argh":"0.1.x","assume":"1.3.x","async-each":"0.1.x","browserify":"11.x.x","http-proxy":"1.11.x","istanbul":"0.3.x","mocha":"2.3.x","mochify":"2.13.x","pre-commit":"1.1.x","setheader":"0.0.x"},"_id":"requests@0.1.7","dist":{"shasum":"7b494f1f5e596016b4393832cedd34659fd1c623","tarball"
	//:"https://r2.cnpmjs.org/requests/-/requests-0.1.7.tgz","integrity":"sha512-LmW8JVyOKef+xdI6DHbXfjh/xnEJjibt5Er4ILADw817hrQ9lKJmk8W8QW3DP6BusJ843lTR1UzznIS4cQXilQ==","signatures":null},"_from":".","_npmVersion":"2.14.3","_npmUser":{"name":"3rdeden","email":"npm@3rd-Eden.com"},"maintainers":[{"name":"3rdeden","email":"npm@3rd-Eden.com"}],"directories
	//":{},"deprecated":""},"0.2.0":{"name":"requests","version":"0.2.0","description":"An streaming XHR abstraction that works in browsers and node.js","main":"index.js","scripts":{"test":"node test/index.js","start":"node test/development.js"},"repository":{"type":"git","url":"git+https://github.com/unshiftio/requests.git"},"keywords":["request","xhr",
	//"requests","http","xml","xmlhttp","xmlhttprequest"],"author":{"name":"Arnout Kazemier","email":""},"license":"MIT","bugs":{"url":"https://github.com/unshiftio/requests/issues"},"homepage":"https://github.com/unshiftio/requests","dependencies":{"axo":"0.0.x","eventemitter3":"~2.0.2","extendible":"0.1.x","hang":"1.0.x","loads":"0.0.x","node-http-xhr"
	//:"~1.2.1","xhr-send":"1.0.x"},"devDependencies":{"argh":"0.1.x","assume":"~1.5.0","async-each":"~1.0.1","browserify":"^14.3.0","http-proxy":"~1.16.2","istanbul":"~0.4.5","mocha":"~3.4.0","mochify":"~2.18.1","pre-commit":"~1.2.0","setheader":"0.0.x"},"_id":"requests@0.2.0","dist":{"shasum":"9797f60ac98836f2a0cad9352fe53f6262ae8189","tarball":"https:
	////r2.cnpmjs.org/requests/-/requests-0.2.0.tgz","integrity":"sha512-3FjmbjEL5XjSwrsPTvLyUOID01GDkP9fFrbvsNe/b6WzIDvjOL3vJyeL87x31793Q6PGJWRiGCVeDhqHazY/Pw==","signatures":null},"_from":".","_npmVersion":"4.1.2","_npmUser":{"name":"3rdeden","email":"npm@3rd-Eden.com"},"maintainers":[{"name":"3rdeden","email":"npm@3rd-Eden.com"}],"directories":{},"dep
	//recated":""},"0.2.1":{"name":"requests","version":"0.2.1","description":"An streaming XHR abstraction that works in browsers and node.js","main":"index.js","scripts":{"test":"node test/index.js","start":"node test/development.js"},"repository":{"type":"git","url":"git+https://github.com/unshiftio/requests.git"},"keywords":["request","xhr","requests
	//","http","xml","xmlhttp","xmlhttprequest"],"author":{"name":"Arnout Kazemier","email":""},"license":"MIT","bugs":{"url":"https://github.com/unshiftio/requests/issues"},"homepage":"https://github.com/unshiftio/requests","dependencies":{"axo":"0.0.x","eventemitter3":"~2.0.2","extendible":"0.1.x","hang":"1.0.x","loads":"0.0.x","node-http-xhr":"~1.2.1"
	//,"xhr-send":"1.0.x"},"devDependencies":{"argh":"0.1.x","assume":"~1.5.0","async-each":"~1.0.1","browserify":"^14.3.0","http-proxy":"~1.16.2","istanbul":"~0.4.5","mocha":"~3.4.0","mochify":"~2.18.1","pre-commit":"~1.2.0","setheader":"0.0.x"},"_id":"requests@0.2.1","dist":{"shasum":"e8748ff39063569a31084ded5f54875e96d91ba8","tarball":"https://r2.cnpm
	//js.org/requests/-/requests-0.2.1.tgz","integrity":"sha512-SlvQm7cl4z285qs5ZrthHjr4TI0Ngb0pzX4jLzSOr7rsA4AlFj+0qhkzF3zKsVBFuU+HseU+iUz4qBA6bV087Q==","signatures":null},"_from":".","_npmVersion":"4.1.2","_npmUser":{"name":"3rdeden","email":"npm@3rd-Eden.com"},"maintainers":[{"name":"3rdeden","email":"npm@3rd-Eden.com"}],"directories":{},"deprecated":
	//""},"0.2.2":{"name":"requests","version":"0.2.2","description":"An streaming XHR abstraction that works in browsers and node.js","main":"index.js","scripts":{"test":"node test/index.js","start":"node test/development.js"},"repository":{"type":"git","url":"git+https://github.com/unshiftio/requests.git"},"keywords":["request","xhr","requests","http",
	//"xml","xmlhttp","xmlhttprequest"],"author":{"name":"Arnout Kazemier","email":""},"license":"MIT","bugs":{"url":"https://github.com/unshiftio/requests/issues"},"homepage":"https://github.com/unshiftio/requests","dependencies":{"axo":"0.0.x","eventemitter3":"~2.0.2","extendible":"0.1.x","hang":"1.0.x","loads":"0.0.x","node-http-xhr":"~1.3.0","xhr-sen
	//d":"1.0.x"},"devDependencies":{"argh":"0.1.x","assume":"~1.5.0","async-each":"~1.0.1","browserify":"^14.3.0","http-proxy":"~1.16.2","istanbul":"~0.4.5","mocha":"~3.4.0","mochify":"~2.18.1","pre-commit":"~1.2.0","setheader":"0.0.x"},"_id":"requests@0.2.2","dist":{"shasum":"0e5ec07fd86b495bdb4beda869b2157eca893b4d","tarball":"https://r2.cnpmjs.org/re
	//quests/-/requests-0.2.2.tgz","integrity":"sha512-V++we6wF8j46aVrbKjcEsRqK6W2XA9RFVtB/k4Mt5wgCqR7EMa2vYCjxInPcBmpfljq94p9tvUB4Y/Vm4Ns+Hw==","signatures":null},"_from":".","_npmVersion":"4.6.1","_npmUser":{"name":"swaagie","email":"info@martijnswaagman.nl"},"maintainers":[{"name":"3rdeden","email":"npm@3rd-Eden.com"}],"directories":{},"deprecated":""
	//},"0.3.0":{"name":"requests","version":"0.3.0","description":"An streaming XHR abstraction that works in browsers and node.js","main":"index.js","scripts":{"test":"node test/index.js","start":"node test/development.js"},"repository":{"type":"git","url":"git+https://github.com/unshiftio/requests.git"},"keywords":["request","xhr","requests","http","x
	//ml","xmlhttp","xmlhttprequest"],"author":{"name":"Arnout Kazemier","email":""},"license":"MIT","bugs":{"url":"https://github.com/unshiftio/requests/issues"},"homepage":"https://github.com/unshiftio/requests","dependencies":{"axo":"0.0.x","eventemitter3":"~4.0.0","extendible":"0.1.x","hang":"1.0.x","loads":"0.0.x","node-http-xhr":"~1.3.0","xhr-send"
	//:"1.0.x"},"devDependencies":{"argh":"0.1.x","assume":"~2.0.0","async-each":"~1.0.1","browserify":"^16.0.0","http-proxy":"~1.17.0","istanbul":"~0.4.5","mocha":"~3.5.0","mochify":"~2.18.1","pre-commit":"~1.2.0","setheader":"~1.0.0"},"_id":"requests@0.3.0","dist":{"shasum":"484913c1648beac3092a2324d8bc296a4bd76c5d","tarball":"https://r2.cnpmjs.org/req
	//uests/-/requests-0.3.0.tgz","integrity":"sha512-1B6nkiHjC1O1cSgFhEwkc+xd8vuj04h7xSmCg5yI8nmhCIKbPkX47od8erQ2pokBt5qxUO7dwP4jplXD6k6ISA==","signatures":null},"_from":"","_npmVersion":"6.6.0","_npmUser":{"name":"swaagie","email":"martijn@swaagman.online"},"maintainers":[{"name":"3rdeden","email":"npm@3rd-Eden.com"}],"directories":{},"deprecated":""}}
	//,"readme":"# requests\n\n[![Made by unshift][made-by]](http://unshift.io)[![Version npm][version]](http://browsenpm.org/package/requests)[![Build Status][build]](https://travis-ci.org/unshiftio/requests)[![Dependencies][david]](https://david-dm.org/unshiftio/requests)[![Coverage Status][cover]](https://coveralls.io/r/unshiftio/requests?branch=maste
	//r)[![IRC channel][irc]](http://webchat.freenode.net/?channels=unshift)\n\n[made-by]: https://img.shields.io/badge/made%20by-unshift-00ffcc.svg?style=flat-square\n[version]: https://img.shields.io/npm/v/requests.svg?style=flat-square\n[build]: https://img.shields.io/travis/unshiftio/requests/master.svg?style=flat-square\n[david]: https://img.shields
	//.io/david/unshiftio/requests.svg?style=flat-square\n[cover]: https://img.shields.io/coveralls/unshiftio/requests/master.svg?style=flat-square\n[irc]: https://img.shields.io/badge/IRC-irc.freenode.net%23unshift-00a8ff.svg?style=flat-square\n\nRequests is a small library that implements fully and true streaming XHR for\nbrowsers that support these me
	//thods. It uses a variety of proprietary\n`responseType` properties to force a streaming connection, even for binary data.\nFor browsers that don't support this we will simply fallback to a regular but\n**async** XHR 1/2 request or ActiveXObject in even older deprecated browsers.\n\n- Internet Explorer \u003e= 10: `ms-stream`\n- FireFox \u003e= 9: `
	//moz-chunked`\n- FireFox \u003c 20: `multipart`\n\nThis module comes with build-in protection against ActiveX blocking that is\nfrequently used in firewalls \u0026 virus scanners.\n\n## Installation\n\nThe module is released in the public npm registry and can be installed using:\n\n```\nnpm install --save requests\n```\n\n## Usage\n\nThe API is a mi
	//x between the Fetch API, mixed with EventEmitter API for the\nevent handling.\n\n```js\n'use strict';\n\nvar requests = require('requests');\n```\n\nNow that we've included the library we can start making requests. The exported\nmethod accepts 2 arguments:\n\n- **url** Required URL that you want to have requested.\n- **options** Optional object wit
	//h additional configuration options:\n  - **streaming** Should we use streaming API's to fetch the data, defaults to\n  `false`.\n  - **method** The HTTP method that should be used to get the contents, defaults\n  to `GET`.\n  - **mode** The request mode, defaults to `cors`\n  - **headers** Object with header name/value that we need to send to the s
	//erver.\n  - **timeout** The timeout in ms before we should abort the request.\n  - **manual** Manually `open` the request, defaults to `false`.\n\n```js\nrequests('https://google.com/foo/bar', { streaming })\n.on('data', function (chunk) {\n  console.log(chunk)\n})\n.on('end', function (err) {\n  if (err) return console.log('connection closed due t
	//o errors', err);\n\n  console.log('end');\n});\n```\n\n## Events\n\nIn the example above you can see the that we're listing to various of events.\nThe following events are emitted:\n\n- `data` A new chunk of data has been received. It can be a small chunk but also\n  the full response depending on the environment it's loaded in.\n- `destroy` The re
	//quest instance has been fully destroyed.\n- `error` An error occurred while requesting the given URL.\n- `end` Done with requesting the URL. An error argument can be supplied if the\n  connection was closed due to an error.\n- `before` Emitted before we send the actual request.\n- `send` Emitted after we've succesfully started the sending of the da
	//ta.\n\n### requests#destroy\n\nDestroy the running XHR request and release all the references that the\n`requests` instance holds. It returns a boolean as indication of a successful\ndestruction.\n\n```js\nrequests.destroy();\n```\n\n### Requests.requested\n\nThe total amount of requests that we've made in this library. It also serves as\nunique id
	// for each request that we store in `.active`.\n\n### Requests.active\n\nAn object that contains all running and active requests. Namespaced under\n`request.requested` id and the requests instance.\n\n## License\n\nMIT\n","maintainers":[{"name":"3rdeden","email":"npm@3rd-Eden.com"},{"name":"swaagie","email":"info@martijnswaagman.nl"}],"time":{"0.0.1
	//":"2014-03-29T05:49:07.412Z","0.1.0":"2015-04-07T09:55:33.997Z","0.1.1":"2015-04-07T12:40:57.798Z","0.1.2":"2015-05-06T18:37:22.794Z","0.1.3":"2015-05-12T13:43:33.928Z","0.1.4":"2015-05-12T18:48:59.325Z","0.1.5":"2015-05-18T18:26:53.425Z","0.1.6":"2015-05-28T08:32:21.371Z","0.1.7":"2015-09-17T14:51:48.929Z","0.2.0":"2017-06-08T15:03:22.39Z","0.2.1"
	//:"2017-06-13T14:04:55.06Z","0.2.2":"2017-06-13T20:35:07.545Z","0.3.0":"2019-08-06T12:17:47.116Z","created":"2021-12-18T20:41:20.218Z","modified":"2021-12-18T20:41:20.218Z"},"homepage":"","keywords":null,"repository":null,"author":{"name":"solos"},"bugs":null,"license":"MIT","readmeFilename":"","users":null,"contributors":null}

}
